In [ ]:

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:

orders = pd.read_csv("/content/olist_orders_dataset.csv")
items = pd.read_csv("/content/olist_order_items_dataset.csv")

print("Orders dataset:", orders.shape)
print("Order items dataset:", items.shape)

Orders dataset: (99441, 8)
Order items dataset: (112650, 7)

In [ ]:

print("ORDERS DATA")
display(orders.head())

print("ORDER ITEMS DATA")
display(items.head())

print("Orders columns:")
print(orders.columns.tolist())

print("Missing values in orders:")
print(orders.isnull().sum())

ORDERS DATA

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

ORDER ITEMS DATA

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

Orders columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Missing values in orders:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:

# Check the number of rows and columns
print("Orders shape:", orders.shape)
print("Order items shape:", items.shape)

# Check column data types
print("\nOrders data types:")
print(orders.dtypes)

print("\nOrder items data types:")
print(items.dtypes)

Orders shape: (99441, 8)
Order items shape: (112650, 7)

Orders data types:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

Order items data types:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [ ]:

# Count duplicate rows
print("Duplicate rows in orders:", orders.duplicated().sum())
print("Duplicate rows in items:", items.duplicated().sum())

# Check duplicate order IDs
print("Duplicate order IDs:", orders["order_id"].duplicated().sum())

Duplicate rows in orders: 0
Duplicate rows in items: 0
Duplicate order IDs: 0

In [ ]:

print("Missing values in orders:")
print(orders.isnull().sum())

print("\nMissing values in order items:")
print(items.isnull().sum())

Missing values in orders:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Missing values in order items:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [ ]:

print(orders["order_status"].value_counts(dropna=False))

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

print(orders[date_columns].dtypes)

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [ ]:

print("Price summary:")
print(items["price"].describe())

print("\nFreight value summary:")
print(items["freight_value"].describe())

print("\nNegative or zero prices:")
print((items["price"] <= 0).sum())

print("\nNegative freight values:")
print((items["freight_value"] < 0).sum())

Price summary:
count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

Freight value summary:
count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

Negative or zero prices:
0

Negative freight values:
0

In [ ]:

print("Price summary:")
print(items["price"].describe())

print("\nFreight value summary:")
print(items["freight_value"].describe())

print("\nNegative or zero prices:")
print((items["price"] <= 0).sum())

print("\nNegative freight values:")
print((items["freight_value"] < 0).sum())

Price summary:
count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

Freight value summary:
count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

Negative or zero prices:
0

Negative freight values:
0

In [ ]:

delivered = orders[orders["order_status"] == "delivered"].copy()

print(
    "Delivered orders with missing actual delivery date:",
    delivered["order_delivered_customer_date"].isna().sum()
)

print(
    "Delivered orders with delivery before purchase:",
    (
        delivered["order_delivered_customer_date"]
        < delivered["order_purchase_timestamp"]
    ).sum()
)

print(
    "Delivered orders with delivery after estimated date:",
    (
        delivered["order_delivered_customer_date"]
        > delivered["order_estimated_delivery_date"]
    ).sum()
)

Delivered orders with missing actual delivery date: 8
Delivered orders with delivery before purchase: 0
Delivered orders with delivery after estimated date: 7826

In [ ]:

for column in ["price", "freight_value"]:
    Q1 = items[column].quantile(0.25)
    Q3 = items[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = items[
        (items[column] < lower_limit) |
        (items[column] > upper_limit)
    ]

    print(f"\n{column}")
    print("Lower limit:", round(lower_limit, 2))
    print("Upper limit:", round(upper_limit, 2))
    print("Potential outliers:", len(outliers))

price
Lower limit: -102.6
Upper limit: 277.4
Potential outliers: 8427

freight_value
Lower limit: 0.98
Upper limit: 33.25
Potential outliers: 12134

In [ ]:

# Create cleaned copies
orders_clean = orders.copy().drop_duplicates()
items_clean = items.copy().drop_duplicates()

# Calculate delivery duration in days
orders_clean["delivery_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

# Identify late deliveries
orders_clean["is_late"] = (
    orders_clean["order_delivered_customer_date"]
    > orders_clean["order_estimated_delivery_date"]
)

# Keep missing delivery classifications unknown
orders_clean.loc[
    orders_clean["order_delivered_customer_date"].isna(),
    "is_late"
] = pd.NA

# Display results
print("Cleaned orders shape:", orders_clean.shape)
print("Cleaned items shape:", items_clean.shape)

print("\nDelivery duration summary:")
print(orders_clean["delivery_days"].describe())

print("\nLate-delivery counts:")
print(orders_clean["is_late"].value_counts(dropna=False))

Cleaned orders shape: (99441, 10)
Cleaned items shape: (112650, 7)

Delivery duration summary:
count    96476.000000
mean        12.558702
std          9.546530
min          0.533414
25%          6.766403
50%         10.217755
75%         15.720327
max        209.628611
Name: delivery_days, dtype: float64

Late-delivery counts:
is_late
False    88649
True      7827
NaN       2965
Name: count, dtype: int64

/tmp/ipykernel_803/1167689833.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  orders_clean.loc[

In [ ]:

# Create a nullable Boolean column
orders_clean["is_late"] = pd.Series(
    pd.NA,
    index=orders_clean.index,
    dtype="boolean"
)

# Only classify delivered orders with both dates available
valid = (
    orders_clean["order_status"].eq("delivered")
    & orders_clean["order_delivered_customer_date"].notna()
    & orders_clean["order_estimated_delivery_date"].notna()
)

orders_clean.loc[valid, "is_late"] = (
    orders_clean.loc[valid, "order_delivered_customer_date"]
    > orders_clean.loc[valid, "order_estimated_delivery_date"]
)

print("Delivered orders with valid dates:", valid.sum())
print("\nLate-delivery counts:")
print(orders_clean.loc[orders_clean["order_status"] == "delivered",
                       "is_late"].value_counts(dropna=False))

Delivered orders with valid dates: 96470

Late-delivery counts:
is_late
False    88644
True      7826
<NA>         8
Name: count, dtype: Int64

In [ ]:

orders_clean.to_csv("/content/cleaned_orders.csv", index=False)
items_clean.to_csv("/content/cleaned_order_items.csv", index=False)

print("Updated datasets saved successfully.")

Updated datasets saved successfully.